
name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
  
    runs-on: windows-latest 
    
    env:
      Solution_Name: NED.Wot.sln                         
      Wap_Project_Directory: NED.WoT.BattleResults.Client  
      Wap_Project_Path: NED.WoT.BattleResults.Client\NED.WoT.BattleResults.Client.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    - name: Install MAUI workload
      run: dotnet workload install maui
      
    - name: Decrypt PFX File
      run: |
        echo "${{ secrets.WINDOWS_PFX_FILE}}" > cert.pfx.asc
        certutil -decode cert.pfx.asc cert.pfx
    
    - name: Add Cert to Store
      run: certutil -user -q -p ${{ secrets.WINDOWS_PFX_PASSWORD }} -importpfx cert.pfx NoRoot

    - name: Build
      run:  dotnet publish NED.WoT.BattleResults.Client\NED.WoT.BattleResults.Client.csproj -c Release -f:net6.0-windows10.0.19041.0

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        path: .\**\AppPackages\**\*.*
     
